### ISSUE TITLE
Join Us

### ISSUE THREAD

**Issue by gautamkrishnar** [mdckerala/Join-Us#1]
Comment on this thread to join Microsoft developer community Kerala GitHub org. Please read the [instructions](https://github.com/mdckerala/Join-Us/blob/master/README.md) first.

**Comment by arunreghunath** [comment]
Hi I'm Arun Reghunath an MSP 2015-16

**Comment by gautamkrishnar** [comment]
@arunreghunath :+1:  added you to the MSP Team.

**Comment by basithhameem** [comment]
Basith Hameem MSP 2k15  :)

**Comment by gautamkrishnar** [comment]
@basithhameem :+1: added
